dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "6"
cache:
  yarn: true
script:
  - yarn run coverage
after_script:
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
